apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-xfce-vnc

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-xfce-vnc

  template:
    metadata:
      labels:
        app: ubuntu-xfce-vnc
    spec:
      containers:
      - image: consol/ubuntu-xfce-vnc
        name: ubuntu-xfce-vnc
        ports:
        - containerPort: 6901
