apiVersion: v1
kind: Service
metadata:
  name: ubuntu-xfce-vnc
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ubuntu-xfce-vnc"
    port: 80
  selector:
    app: ubuntu-xfce-vnc
